language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: nkyono-github
    token:
      secure: ae00c0c080b3d8a4404609d53baf53576b039887
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
